/* 
 * File:   mcal_interrupt_gen.h
 * Author: Lenovo
 *
 * Created on August 9, 2023, 11:52 AM
 */

#ifndef MCAL_INTERRUPT_GEN_H
#define	MCAL_INTERRUPT_GEN_H

/*Interrupt usage*/
#define USE_INTERRUPT
/*PRIORITY*/
//#define INTERRUPT_PRIORITY_LEVELS_ENABLE

/*External*/
#define EXTERNAL_INTERRUPT_ENABLE
#define EXTERNAL_ON_CHANGE_INTERRUPT_ENABLE

/*Internal*/
#define ADC_INTERRUPT_FEATURE
#define TIMER0_INTERRUPT_FEATURE
#define TIMER1_INTERRUPT_FEATURE
#define TIMER2_INTERRUPT_FEATURE
#define TIMER3_INTERRUPT_FEATURE
#define CCP1_INTERRUPT_FEATURE
#define CCP2_INTERRUPT_FEATURE
#define EUSART_RX_INTERRUPT_FEATURE
#define EUSART_TX_INTERRUPT_FEATURE
//#define MSSP_I2C_INTERRUPT_FEATURE
//#define MSSP_I2C_BUS_COL_INTERRUPT_FEATURE
#endif	/* MCAL_INTERRUPT_GEN_H */

